image: docker:stable

services:
  - name: docker:dind
    command: ["--insecure-registry", "$CI_REGISTRY"]

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: ${CI_REGISTRY}/sample-express
  CONTAINER_NAME: sample-express

cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - oci-arm4c-runner-tag
  script:
    - "docker login -u \"${CI_REGISTRY_USER}\" -p \"${CI_REGISTRY_PASSWORD}\" \"${CI_REGISTRY}\""
    - ls -al
    - docker container ls -a
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  tags:
    -  oci-arm4c-runner-tag
  script:
    - docker container ls -a
    - docker container rm -f $CONTAINER_NAME || true docker run -d -p 8900:8900 --name $CONTAINER_NAME --restart always $IMAGE_NAME
    - docker container ls -a
